name: 이슈 템플릿
description: 이슈 생성 시 사용하는 템플릿입니다
title: 제목을 입력하세요.
labels:
  - feature
assignees:
  - chasj0326
body:
  - type: input
    attributes:
      label: 한 줄 요약
      placeholder: 이슈 내용을 한 줄로 작성해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 작업 리스트
      value: |
        - [ ] 
        - [ ]
        - [ ]
  - type: textarea
    attributes:
      label: 기타 설명
      placeholder: 추가 설명이 있다면 입력!
