name: 이슈 템플릿
description: 이슈 생성 시 사용하는 템플릿입니다
title: 제목을 입력하세요.
labels:
  - feature
assignees:
  - chasj0326
body:
  - type: markdown
    attributes:
      value: |
        ## 기능 한줄 설명

        - [ ] 하위 항목
        - [ ] 하위 항목

  - type: textarea
    attributes:
      label: 기타 사항
      placeholder: 기타 내용이 있다면 입력해주세요.
