import type { Metadata } from 'next';
import './globals.css';
import { Nanum_Gothic } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Juang App',
  description: 'Generated by create next app',
};

const nanumGothic = Nanum_Gothic({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-nanum',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`h-svh bg-gray-light ${nanumGothic.className}`}>
        <main className='inset-0 h-full overflow-auto m-auto bg-white sm:aspect-[9/16] text-sm'>{children}</main>
      </body>
    </html>
  );
}
