import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import { cookies } from "next/headers";
import TanStackQueryProvider from "@/providers/TanStackQueryProvider";
import { AnimationContainer } from "@/components";
import { CustomToastContainer } from "@/components/CustomToast";
import { apiServer } from "@/api/instance";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Juang App",
  description: "Generated by create next app",
};

const nanumGothic = Nanum_Gothic({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`h-svh bg-gray-light ${nanumGothic.className}`}>
        <main className="inset-0 h-full overflow-auto m-auto bg-white sm:aspect-[9/16] text-black-soft min-w-[300px]">
          <TanStackQueryProvider>
            <AnimationContainer />
            {children}
          </TanStackQueryProvider>
          <CustomToastContainer fontClassName={nanumGothic.className} />
        </main>
      </body>
    </html>
  );
}

const AUTH_TOKEN_KEY = process.env.AUTH_TOKEN_KEY ?? "";
apiServer.beforeRequest(async (configs) => {
  const cookie = await cookies();
  const token = cookie.get(AUTH_TOKEN_KEY)?.value;
  const requestHeaders = new Headers(configs.headers);

  if (token) {
    requestHeaders.set("Authorization", `Bearer ${token}`);
  } else {
    requestHeaders.delete("Authorization");
    cookie.delete(AUTH_TOKEN_KEY);
  }
  return { ...configs, headers: requestHeaders };
});
