name: Auto-Close Issues on Develop Merge

on:
  pull_request:
    types: [closed]

jobs:
  close-issues:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug PR Information
        run: |
          echo "Pull Request Body: ${{ github.event.pull_request.body }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Merged: ${{ github.event.pull_request.merged }}"

      - name: Close linked issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event.pull_request.body }}" =~ close[[:space:]]#([0-9]+) ]]; then
            ISSUE_NUMBER=${BASH_REMATCH[1]}
            echo "Closing Issue: $ISSUE_NUMBER"
            curl -X PATCH \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER \
              -d '{"state": "closed"}'
          else
            echo "No issue to close found in PR body."
          fi
