name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH - Git pull & install
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            source ~/.nvm/nvm.sh
            cd ~/juang_client
            nvm use --lts
            git pull origin main
            npm install

      - name: SSH - Build
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          command_timeout: 600s
          script: |
            source ~/.nvm/nvm.sh
            cd ~/juang_client
            nvm use --lts
            npm run build:deploy

      - name: SSH - Restart app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            source ~/.nvm/nvm.sh
            cd ~/juang_client
            nvm use --lts
            pm2 restart next-app
